"""empty message

Revision ID: 1187dc91709e
Revises: 928401a3f061
Create Date: 2022-04-15 11:06:30.019725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1187dc91709e'
down_revision = '928401a3f061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_meetings', 'confirmed_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_meetings', sa.Column('confirmed_players', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
