"""empty message

Revision ID: 3c569a7565c1
Revises: 8184f895c4ae
Create Date: 2022-04-11 11:57:23.386250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c569a7565c1'
down_revision = '8184f895c4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_autor_key', 'news', type_='unique')
    op.create_unique_constraint(None, 'news', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.create_unique_constraint('news_autor_key', 'news', ['autor'])
    # ### end Alembic commands ###
