"""empty message

Revision ID: 458f07a050c0
Revises: c033c0407ef9
Create Date: 2022-04-15 12:36:25.638750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458f07a050c0'
down_revision = 'c033c0407ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_meetings', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_meetings', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
