"""empty message

Revision ID: 62e7708e6385
Revises: 458f07a050c0
Create Date: 2022-04-15 12:36:54.959035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e7708e6385'
down_revision = '458f07a050c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_meetings', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_meetings', 'deleted')
    # ### end Alembic commands ###
