"""added games models

Revision ID: 6c1a319c4099
Revises: dec1a6d08b2e
Create Date: 2022-03-28 11:04:35.262459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1a319c4099'
down_revision = 'dec1a6d08b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meeting_users_meeting_id'), 'meeting_users', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_users_user_id'), 'meeting_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_meeting_users_user_id'), table_name='meeting_users')
    op.drop_index(op.f('ix_meeting_users_meeting_id'), table_name='meeting_users')
    # ### end Alembic commands ###
