"""add city_name to GameMeeting

Revision ID: 8b8867a23c67
Revises: 9ef751e716ee
Create Date: 2022-04-05 22:16:45.999805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8867a23c67'
down_revision = '9ef751e716ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_meetings', sa.Column('city_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_game_meetings_city_name'), 'game_meetings', ['city_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_meetings_city_name'), table_name='game_meetings')
    op.drop_column('game_meetings', 'city_name')
    # ### end Alembic commands ###
