"""empty message

Revision ID: 8d8b154bf023
Revises: 1187dc91709e
Create Date: 2022-04-15 11:08:03.370008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d8b154bf023'
down_revision = '1187dc91709e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_meetings', sa.Column('number_of_subs', sa.Integer(), nullable=True))
    op.drop_column('game_meetings', 'subscribed_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_meetings', sa.Column('subscribed_players', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('game_meetings', 'number_of_subs')
    # ### end Alembic commands ###
