"""empty message

Revision ID: 99e3b123b6b8
Revises: 56cca23cb8b5
Create Date: 2022-03-29 23:19:52.089923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e3b123b6b8'
down_revision = '56cca23cb8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_meetings', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_game_meetings_game_id'), 'game_meetings', ['game_id'], unique=False)
    op.create_foreign_key(None, 'game_meetings', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_meetings', type_='foreignkey')
    op.drop_index(op.f('ix_game_meetings_game_id'), table_name='game_meetings')
    op.drop_column('game_meetings', 'game_id')
    # ### end Alembic commands ###
