"""empty message

Revision ID: b49bcce135d0
Revises: 3c569a7565c1
Create Date: 2022-04-11 13:13:06.224735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49bcce135d0'
down_revision = '3c569a7565c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author', sa.String(), nullable=False))
    op.drop_column('news', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('autor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('news', 'author')
    # ### end Alembic commands ###
