"""added games models

Revision ID: c31062504b23
Revises: dec1a6d08b2e
Create Date: 2022-03-28 11:03:35.983103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c31062504b23'
down_revision = 'dec1a6d08b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links_from_hg')
    op.drop_table('games_hg')
    op.create_index(op.f('ix_meeting_users_meeting_id'), 'meeting_users', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_users_user_id'), 'meeting_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_meeting_users_user_id'), table_name='meeting_users')
    op.drop_index(op.f('ix_meeting_users_meeting_id'), table_name='meeting_users')
    op.create_table('games_hg',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_players', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links_from_hg.id'], name='games_hg_link_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_hg_pkey')
    )
    op.create_table('links_from_hg',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='links_from_hg_pkey'),
    sa.UniqueConstraint('link', name='links_from_hg_link_key')
    )
    # ### end Alembic commands ###
